apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.letsencrypt.acme.email=aniskydev@protonmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    
    ports:
      web:
        expose: true
        exposedPort: 80
        middlewares:
          - redirect-www@file
      websecure:
        expose: true
        exposedPort: 443
        middlewares:
          - redirect-www@file
      traefik:
        expose: true
        exposedPort: 9000
    
    service:
      type: LoadBalancer
    
    providers:
      file:
        enabled: true
        content: |
          http:
            middlewares:
              redirect-www:
                redirectRegex:
                  regex: "^https://www\\.(.+)"
                  replacement: "https://${1}"
                  permanent: true